# Generated by Django 3.2.9 on 2021-11-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('unit_price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
